name: CI

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
      with:
        components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Component.VC.CoreIde;Microsoft.VisualStudio.Component.Windows10SDK
    - name: MSBuild
      working-directory: src
      run: msbuild SharpGit.sln
